# GENERATED by 'make ci-smp-refresh' -- do not edit by hand.
# Each entry is <name>:<bin in bins/>:<exit PC>, read from the
# linked ELF with nm so it cannot drift from the committed bin.
CI_SMP_TESTS := \
  mt-llist:mt-llist-q4.bin:0x80000bdc \
  mt-seqlock:mt-seqlock-q4.bin:0x80000ab4 \
  mt-spinwait:mt-spinwait-q4.bin:0x80000a8c \
  mt-fencei:mt-fencei-q4.bin:0x80000b7c \
  mt-crosscall:mt-crosscall-q4.bin:0x80000cec \
  mt-illegal:mt-illegal-q4.bin:0x800008cc \
  mt-icoh-cross:mt-icoh-cross-q4.bin:0x80000a64 \
  mt-icoh-self:mt-icoh-self-q4.bin:0x80000a68 \

