name: Build and Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Install Verilator
      run: |
        sudo apt-get install -y verilator

    - name: Install Make
      run: |
        sudo apt-get install -y make

    - name: Install SBT
      run: |
        echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add
        sudo apt-get update && sudo apt-get install sbt -y

    - name: Run all standard simulation
      run: |
        make clean
        make sim
        make runLockStepTest
        make test_all_images

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.txt
